name: Comment_Ci
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - CommentProj
  pull_request:
    branches:
      - CommentProj
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Install husky
        run: npm run prepare




